DATASET: LoaderZLS
ROOT: data/datasets/voc12/dataset
IGNORE_LABEL: 255
VAL_SIZE: 500

IMAGE:
    MEAN:
        R: 122.675
        G: 116.669
        B: 104.008
    SIZE:
        TRAIN: 321
        TEST: 513

SPLIT:
    TRAIN: train
    VAL: val
    TEST: novel

# Model definition
N_CLASSES: 20
N_BLOCKS: [3, 4, 23, 3]
PYRAMIDS: [6, 12, 18, 24]

# Training setting
BATCH_SIZE:
    TRAIN: 5
    TEST: 60
ITER_MAX: 500
ITER_SIZE: 2
ITER_SAVE: [ 100 250 500 ]
ITER_TB: 10
LR_DECAY: 10
LR: 7.5e-5
MOMENTUM: 0.9
OPTIMIZER: sgd
POLY_POWER: 0.9
WEIGHT_DECAY: 5.0e-4

INIT_MODEL: /BS/subhc/work/zss/deeplab-pytorch/data/models/deeplab_resnet101/init/deeplabv2_resnet101_init.pth
SAVE_DIR: .
LOG_DIR: runs/pascal-voc
NUM_WORKERS: 0
WARP_IMAGE: True
